

# This file was *autogenerated* from the file gamble.sage
from sage.all_cmdline import *   # import sage library

_sage_const_999999 = Integer(999999); _sage_const_20 = Integer(20); _sage_const_31 = Integer(31); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_12 = Integer(12); _sage_const_65537 = Integer(65537); _sage_const_0x80 = Integer(0x80); _sage_const_8 = Integer(8); _sage_const_32 = Integer(32)
from hashlib import sha256
import sys
sys.setrecursionlimit(_sage_const_999999 )

def build_except_key_header(basename: str, body_nonce: bytes):
    basename_sha = sha256(basename.encode()).digest()
    bodynonce_sha = sha256(body_nonce).digest()
    return basename_sha + bodynonce_sha

def build(basename: str, header_nonce: bytes, body_nonce: bytes, key: bytes):
    return build_except_key_header(basename, body_nonce) + header_nonce + key

def recover_m_by_modgcd(c1, c2, K, e, N, n_primes=_sage_const_20 , bits=_sage_const_31 ):
    roots, mods = [], []
    used = _sage_const_0 
    while used < n_primes:
        p = next_prime(ZZ.random_element(_sage_const_2 **(bits-_sage_const_1 ), _sage_const_2 **bits))
        if gcd(p, N) != _sage_const_1  or gcd(e, p) == _sage_const_0 :
            continue
        Fp = GF(p); R = PolynomialRing(Fp, names=('X',)); (X,) = R._first_ngens(1)
        f = X**e - Fp(c1); g = (X + Fp(K))**e - Fp(c2)
        d = f.gcd(g)
        if d.degree() != _sage_const_1 :
            continue
        mp = (-d.monic()[_sage_const_0 ]) % p
        roots.append(mp); mods.append(p)
        used += _sage_const_1 
    m = crt(roots, mods) % N
    # 검증
    if pow(m, e, N) != c1 % N: raise ValueError("fail v1")
    if pow((m + K) % N, e, N) != c2 % N: raise ValueError("fail v2")
    return ZZ(m)

if __name__ == "__main__":

    from Crypto.Util.number import bytes_to_long, long_to_bytes
    
    flag_png_nonce = b"\\" * _sage_const_12 
    defence_png_nonce = b"\xf8" * _sage_const_12 

    N = bytes.fromhex("d7dd82fdc6921c455c92033bb6f51045afe2ba908c3c13c643b7bc87f96135dbe9a97c364ad5a82e47a1556860f170147a6f9f9fdaf4f308fc6bccf57a7d86582b2794c19c90839c3cfcbe75edbc57e7125e378ccce1d6c320e6983361fd6cb1e5ae78520384979dca7461c7b2574153d9ff4bdb47e60bbe9728b9d51c491a69")
    N = bytes_to_long(N)
    e = _sage_const_65537 

    with open('defence.png.CCE2025', 'rb') as f:
        c1 = bytes_to_long(f.read()[-_sage_const_0x80 :])
    with open('flag.png.CCE2025', 'rb') as f:
        c2 = bytes_to_long(f.read()[-_sage_const_0x80 :])

    R = PolynomialRing(Zmod(N), names=('X',)); (X,) = R._first_ngens(1)

    A = bytes_to_long(build_except_key_header("defence.png", defence_png_nonce))
    B = bytes_to_long(build_except_key_header("flag.png", flag_png_nonce))
    K = ((B - A) * _sage_const_2 **(_sage_const_8  * (_sage_const_32  + _sage_const_12 ))) % N

    g1 = X**e - c1
    g2 = (X + K)**e - c2
    while g2 != _sage_const_0 :
        g1, g2 = g2, g1 % g2
        print(g2.degree())
    
    flag = ZZ(-g1.monic()[_sage_const_0 ])

    print(long_to_bytes(flag))

